//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjectNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int WorksID { get; set; }
        public string unvan { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    }
}
